spring:
  application:
    name: eshop-product-service
  data:
    mongodb:
      username: ${ORDER_SERVICE_QUERY_DB_USERNAME}
      password: ${ORDER_SERVICE_QUERY_DB_PASSWORD}
      authentication-database: admin
      database: products
  cloud:
    consul:
      host: ${CONSUL_URL:localhost}
      port: 8500
      config:
        enabled: false
      discovery:
        enabled: true
        health-check-path: /actuator/health
        health-check-interval: 10s
        instance-id: ${spring.application.name}:${random.value}
        register: true
        prefer-ip-address: true
        tags:
          - traefik.enable=true
          - traefik.http.routers.eshop-product-service.rule=PathPrefix(`/api/v1/products`)
          - traefik.http.services.eshop-product-service.loadbalancer.server.port=8084
server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus