spring:
  application:
    name: eshop-auth-service

  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        enabled: false
      discovery:
        enabled: true
        health-check-path: /actuator/health
        health-check-interval: 10s
        instance-id: ${spring.application.name}:${random.value}
server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "health"