spring:
  application:
    name: eshop-auth-service
  jpa:
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:${USER_SERVICE_DB_PORT}/${USER_SERVICE_DB}
    username: ${USER_SERVICE_DB_USERNAME}
    password: ${USER_SERVICE_DB_PASSWORD}

  cloud:
    consul:
      host: ${CONSUL_URL:localhost}
      port: 8500
      config:
        enabled: false
      discovery:
        enabled: true
        health-check-path: /actuator/health
        health-check-interval: 10s
        instance-id: ${spring.application.name}:${random.value}
        tags:
          - traefik.enable=true
          - traefik.http.routers.eshop-auth-service.rule=PathPrefix(`/api/v1/users`)
          - traefik.http.services.eshop-auth-service.loadbalancer.server.port=8081
        register: true
        prefer-ip-address: true
server:
  port: 8081
logging:
  level:
    org:
      springframework:
        cloud:
          consul: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, httpexchanges