spring:
  application:
    name: eshop-auth-service
  jpa:
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${USER_SERVICE_DB_HOST}:${USER_SERVICE_DB_PORT}/${USER_SERVICE_DB}
    username: ${USER_SERVICE_DB_USERNAME}
    password: ${USER_SERVICE_DB_PASSWORD}

  cloud:
    consul:
      host: ${CONSUL_URL:localhost}
      port: 8500
      config:
        enabled: false
      discovery:
        enabled: true
        health-check-path: /actuator/health
        health-check-interval: 10s
        instance-id: ${spring.application.name}:${random.value}
        tags:
          - traefik.enable=true
          - "traefik.http.routers.eshop-auth-service.rule=PathPrefix(`/api/v1/users`) || PathPrefix(`/oauth2`)"
          - traefik.http.services.eshop-auth-service.loadbalancer.server.port=8088
        register: true
        prefer-ip-address: true
eshop:
  service-client:
    secret: ${ESHOP_SERVICE_CLIENT_SECRET}

bff:
  token-uri: http://localhost:8088/oauth2/token
  client-id: eshop-web-client
  redirect-uri: http://localhost:8088/bff/callback
  spa-redirect-uri: http://localhost:3000
  cookie:
    same-site: Lax
    secure: false

server:
  port: 8088
logging:
  level:
    org:
      springframework:
        cloud:
          consul: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, httpexchanges, prometheus