spring:
  application:
    name: eshop-auth-service

  cloud:
    consul:
      host: ${CONSUL_URL:localhost}
      port: 8500
      config:
        enabled: false
      discovery:
        enabled: true
        health-check-path: /actuator/health
        health-check-interval: 10s
        instance-id: ${spring.application.name}:${random.value}
        tags:
          - traefik.enable=true
          - traefik.http.routers.eshop-auth-service.rule=PathPrefix(`/user`)
          - traefik.http.services.eshop-auth-service.loadbalancer.server.port=8081
        register: true
        prefer-ip-address: true
server:
  port: 8081
logging:
  level:
    org:
      springframework:
        cloud:
          consul: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "health"