version: '3.7'

services:
  mongodb:
      image: mongo
      environment:
         MONGO_INITDB_ROOT_USERNAME: ${ORDER_SERVICE_QUERY_DB_USERNAME}
         MONGO_INITDB_ROOT_PASSWORD: ${ORDER_SERVICE_QUERY_DB_PASSWORD}
      env_file: dev.env
      ports:
        - "27017:27017"
  order-service-db:
      image: postgres
      ports:
        - "5433:5432"
      environment:
        POSTGRES_PASSWORD: ${ORDER_SERVICE_DB_PASSWORD}
        POSTGRES_DB: ${ORDER_SERVICE_DB}
      env_file: "dev.env"
      volumes:
        - order_service_db:/var/lib/postgresql/data

  traefik:
    image: traefik:v3.4 
    depends_on:
      - consul
    network_mode: host
    volumes:
      - ./traefik/traefik-dev.yml:/etc/traefik/traefik.yml
      - ./logs:/logs

  consul:
    container_name: consul
    image: hashicorp/consul
    network_mode: host
  
volumes:
  user_service_db:
  order_service_db: 
 
networks:
  elastic:
    driver: bridge