version: '3.7'

services:

  user-service:
    image: user-service.dev
    build:
      context: ../eshop-user-service
      dockerfile: Dockerfile
    depends_on:
      - user-service-db
    env_file: "test.env"

  user-service-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${USER_SERVICE_DB_PASSWORD}
      POSTGRES_DB: ${USER_SERVICE_DB}
    env_file: "test.env"
    volumes:
      - user_service_db_dev:/var/lib/postgresql/data
      # - ./sql/user_service:/docker-entrypoint-initdb.d
    logging:
      driver: fluentd
      options:
        fluentd-address: fluent-bit:24224
        fluentd-async: "true"

  user-service-db-exporter:
    image: bitnami/postgres-exporter
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_NAME: "postgres://${USER_SERVICE_DB_USERNAME}:${USER_SERVICE_DB_PASSWORD}@user-service-db/${USER_SERVICE_DB}?sslmode=disable"
    depends_on:
      user-service-db:
        condition: service_started
  
  order-service:
    image: order-service.dev
    build:
      context: ../eshop-order-service
      dockerfile: Dockerfile.dev
    depends_on:
      - order-service-db
    env_file: "test.env"

  order-service-db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${ORDER_SERVICE_DB_PASSWORD}
      POSTGRES_DB: ${ORDER_SERVICE_DB}
    env_file: "dev.env"
    volumes:
      - order_service_db_dev:/var/lib/postgresql/data
      # - ./sql/order_service:/docker-entrypoint-initdb.d

  traefik:
    image: traefik:v3.4
    ports:
      - "8080:8080"
      - "80:80"
    depends_on:
      - consul
    volumes:
      - ./traefik/traefik-test.yml:/etc/traefik/traefik.yml
      - ./logs:/logs

  consul:
    container_name: consul
    image: hashicorp/consul
    ports:
      - "8500:8500"
  prometheus:
    image: prom/prometheus
    volumes:
      - eshop_prometheus_dev:/prometheus
      - ./test/prometheus/:/etc/prometheus/
    ports:
      - "9090:9090"
  grafana:  
    image: grafana/grafana
    volumes:
      - eshop_grafana_data_dev:/var/lib/grafana

  order-service-query-db:
    image: mongo
    environment:
       MONGO_INITDB_ROOT_USERNAME: ${ORDER_SERVICE_QUERY_DB_USERNAME}
       MONGO_INITDB_ROOT_PASSWORD: ${ORDER_SERVICE_QUERY_DB_PASSWORD}
    ports:
      - "27017:27017"

  kafka:
    image: apache/kafka
    ports:
      - "9092:9092"
  schema-registry:
    image: confluentinc/cp-schema-registry
    hostname: schema-registry
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.2
    container_name: elasticsearch
    hostname: elasticsearch-node
    environment:
      - discovery.type=single-node 
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - eshop_elasticsearch_data_dev:/usr/share/elasticsearch/data


  kibana:
    image: docker.elastic.co/kibana/kibana:8.18.2
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS:https://elasticsearch:9200
    volumes:
      - eshop_kibana_data_dev:/usr/share/kibana/data
    ports:
      - "5601:5601" 
  fluent-bit:
    image: fluent/fluent-bit
    container_name: fluent-bit
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./infrastructure/fluent-bit-elastic.conf:/fluent-bit/etc/fluent-bit.conf

volumes:
  user_service_db_dev:
  order_service_db_dev:
  eshop_prometheus_dev:
  eshop_elasticsearch_data_dev:
  eshop_kibana_data_dev:
  eshop_grafana_data_dev: