version: '3.7'

services:
  traefik:
    image: traefik:v3.4
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml

  consul:
    container_name: consul
    image: hashicorp/consul
    ports:
      - "8500:8500"

  user-service:
    container_name: eshop-user-service
    build: ../eshop-user-service
    ports:
      - "8081:8081"